---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: proxmox-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-tv-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: "nfs"
  volumeName: nfs-media-tv
