apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: "0.5.4"
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi-plugin
        namespace: csi-proxmox
      interval: 5m
  releaseName: proxmox-csi-plugin
  targetNamespace: csi-proxmox
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
