apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  data:
    - secretKey: token_secret
      remoteRef:
        key: kubernetes/production/csi-proxmox/proxmox-csi-plugin
        property: token_secret
