apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.zech.co
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-development
          role: external-secrets-development
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
