---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: core-traefik-config
    - name: core-cert-manager-config
    - name: core-proxmox-csi-config
    - name: core-cnpg-controller
    - name: base
  interval: 10m
  path: ./clusters/production/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 30m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
