---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-proxmox-csi-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/proxmox-csi/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metallb-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/metallb/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/cert-manager/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-traefik-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: core-metallb-controller
    - name: core-cert-manager-controller
  interval: 10m
  path: ./clusters/production/core/traefik/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cnpg-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/cnpg/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-checkmk-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/checkmk/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-metallb-controller
  interval: 10m
  path: ./clusters/production/core/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-cert-manager-controller
    - name: core-traefik-controller
  interval: 10m
  path: ./clusters/production/core/cert-manager/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-traefik-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-traefik-controller
  interval: 10m
  path: ./clusters/production/core/traefik/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-proxmox-csi-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-proxmox-csi-controller
  interval: 10m
  path: ./clusters/production/core/proxmox-csi/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-checkmk-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-checkmk-controller
    - name: core-traefik-controller
  interval: 10m
  path: ./clusters/production/core/checkmk/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
