apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.3.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: linuxserver/jellyseerr
              tag: "2.7.3"

            env:
              TZ: "Europe/Vienna"

    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: 5055

    persistence:
      config:
        enabled: true
        existingClaim: jellyseerr-config-pvc
        globalMounts:
          - path: /config
