apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: cnpg-system
      interval: 5m
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    installCRDs: true
