apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jellystat-database
  namespace: auth
spec:
  instances: 3

  storage:
    size: 10Gi
    storageClass: "longhorn"

  bootstrap:
    initdb:
      database: jellystat
      owner: jellystat
