apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellystat-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: proxmox-csi
