apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellystat
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.3.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      jellystat:
        containers:
          app:
            image:
              repository: cyfershepard/jellystat
              tag: "1.1.6"

            env:
              TZ: "Europe/Vienna"

    service:
      app:
        controller: jellystat
        ports:
          http:
            port: 3000

    persistence:
      config:
        enabled: true
        existingClaim: jellystat-config-pvc
        globalMounts:
          - path: /config
