apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: proxmox-csi-plugin
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.yaml: |
          clusters:
          - url: "https://pve.local.zech.co:8006/api2/json"
            insecure: false
            token_id: "kubernetes-csi@pve!csi"
            token_secret: "{{ .token_secret | toString }}"
            region: "pve"
  data:
    - secretKey: token_secret
      remoteRef:
        key: kubernetes/ENV/csi-proxmox/proxmox-csi-plugin
        property: token_secret
