---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: auth-quota
  namespace: auth
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: auth-limit-range
  namespace: auth
spec:
  limits:
    - max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: "10m"
        memory: 64Mi
      default:
        cpu: "500m"
        memory: 512Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      type: Container
    - max:
        cpu: "4"
        memory: 8Gi
      min:
        cpu: "10m"
        memory: 64Mi
      type: Pod
