---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: media-quota
  namespace: media
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: media-limit-range
  namespace: media
spec:
  limits:
    - max:
        cpu: "4"
        memory: 8Gi
      min:
        cpu: "10m"
        memory: 64Mi
      default:
        cpu: "500m"
        memory: 512Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      type: Container
    - max:
        cpu: "8"
        memory: 16Gi
      min:
        cpu: "10m"
        memory: 64Mi
      type: Pod
